[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/__cms/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/functions/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

# A redirect rule with many of the supported properties
[[redirects]]
  from = "/"
  to = "/de"
  status = 301
  force = true
  conditions = {Language = ["de"], Country = ["DE"]}

[images]
  remote_images = ["https://a.storyblok.com/.*"]