[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/__cms/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/functions/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

[images]
  remote_images = ["https://a.storyblok.com/.*"]