export const components = {
  // Content types generating pages
  JobPosting: 'components/pages/JobPosting',
  KnowledgeBaseArticle: 'components/pages/KnowledgeBaseArticle',
  NewsArchive: 'components/pages/NewsArchive',
  NewsArticle: 'components/pages/NewsArticle',
  Page: 'components/pages/Page',
  Project: 'components/pages/Project',
  ProjectArchive: 'components/pages/ProjectArchive',
  // Sections
  Accordion: 'components/sections/Accordion',
  AnchorNavigation: 'components/storyblok/FallbackComponent',
  CallToAction: 'components/sections/CallToAction',
  ContactPerson: 'components/sections/ContactPerson',
  EntryCarousel: 'components/storyblok/FallbackComponent',
  EntryList: 'components/storyblok/FallbackComponent',
  HomePageHero: 'components/sections/HomePageHero',
  ImageCard: 'components/storyblok/FallbackComponent',
  ImageCarousel: 'components/sections/ImageCarousel',
  ImageDouble: 'components/sections/ImageDouble',
  ImageSingle: 'components/sections/ImageSingle',
  ImageTeaser: 'components/sections/ImageTeaser',
  ItemList: 'components/sections/ItemList',
  LinkList: 'components/sections/LinkList',
  MediaGrid: 'components/sections/MediaGrid',
  MediaQuartet: 'components/sections/MediaQuartet',
  Stats: 'components/storyblok/FallbackComponent',
  TextBlock: 'components/sections/TextBlock',
  PageHero: 'components/sections/PageHero',
  TextCarousel: 'components/sections/TextCarousel',
  TextImage: 'components/sections/TextImage',
  Video: 'components/storyblok/FallbackComponent',
  // Baked sections
  JobPostingList: 'components/sections/JobPostingList',
  NewsCarousel: 'components/sections/NewsCarousel',
  LatestProjectsCarousel: 'components/sections/LatestProjectsCarousel',
  ProjectCarousel: 'components/sections/ProjectCarousel',
  // App owned sections
  JobHero: 'components/sections/JobHero',
  KnowledgeBaseHero: 'components/storyblok/FallbackComponent',
  NewsHero: 'components/sections/NewsHero',
  ProjectHero: 'components/sections/ProjectHero',
  // Components
  AccordionItem: 'components/sections/AccordionItem',
  HomePageHeroItem: 'components/shared/HomePageHeroItem',
  Image: 'components/shared/Image',
  ImageAspectRatio: 'components/sections/ImageAspectRatio',
  ItemListItem: 'components/sections/ItemListItem',
  Media: 'components/shared/Media',
  Quote: 'components/sections/Quote',
  TestImage: 'components/shared/TestImage',
  TextCard: 'components/sections/TextCard',
  TextHeadlineCard: 'components/sections/TextHeadlineCard',
  HeadlineCard: 'components/sections/HeadlineCard',
  // RichText Blocks
  RichTextButton: 'components/sections/RichTextButton',
}

export const componentNames = Object.keys(components)
